# Docker compose start container with env variables
services:
  local-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=itjustworks
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    # volumes: # uncomment to persist data using bind mount
    # - ./data:/var/lib/postgresql/data
    # volumes: # uncomment to persist data using named volume
    #   - local-db-data:/var/lib/postgresql/data

  api-server:
    image: lms-public-api
    build: api/
    environment:
      - MODE=local
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:itjustworks@local-db:5432/mydb
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - local-db

  web-server:
    image: lms-web
    build: webapp/
    environment:
      - MODE=local
      - API_URL=http://api-server:8080
    ports:
      - "3000:80"
    depends_on:
      - api-server
# volumes:
#   local-db-data: # uncomment to persist data using named volume
